name: publish

on:
  push:
    branches:
      - doxy-gh-pages

jobs:

  create-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: False
      - name: Set up doxygen
        run: >-
          wget https://www.doxygen.nl/files/doxygen-1.13.2.src.tar.gz;
          gunzip doxygen-1.13.2.src.tar.gz;
          tar xf doxygen-1.13.2.src.tar;
          cd doxygen-1.13.2;
          mkdir build;
          cd build;
          cmake -G "Unix Makefiles" ..;
          make;
      - name: Build documentation
        run: >-
          cd doxygen/;
          doxygen Doxyfile;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: doxygen/HTML

  deploy-docs:
    needs:
      - create-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: doxygen/HTML

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4