name: publish

on:
  push:
    branches:
      - doxy-gh-pages

jobs:

  create-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: False
      - name: Set up doxygen
        run: >-
          echo "test"
      - name: Build documentation
        run: >-
          mkdir _build/; echo "Hello world!" > _build/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _build/

  deploy-docs:
    needs:
      - create-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: _build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4